/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ResultHashRouteImport } from './routes/result.$hash'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultHashRoute = ResultHashRouteImport.update({
  id: '/result/$hash',
  path: '/result/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/evidence': typeof EvidenceRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/verify': typeof VerifyRoute
  '/result/$hash': typeof ResultHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/evidence': typeof EvidenceRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/verify': typeof VerifyRoute
  '/result/$hash': typeof ResultHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/evidence': typeof EvidenceRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/verify': typeof VerifyRoute
  '/result/$hash': typeof ResultHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/evidence'
    | '/register'
    | '/scan'
    | '/verify'
    | '/result/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/evidence'
    | '/register'
    | '/scan'
    | '/verify'
    | '/result/$hash'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/evidence'
    | '/register'
    | '/scan'
    | '/verify'
    | '/result/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  EvidenceRoute: typeof EvidenceRoute
  RegisterRoute: typeof RegisterRoute
  ScanRoute: typeof ScanRoute
  VerifyRoute: typeof VerifyRoute
  ResultHashRoute: typeof ResultHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$hash': {
      id: '/result/$hash'
      path: '/result/$hash'
      fullPath: '/result/$hash'
      preLoaderRoute: typeof ResultHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  EvidenceRoute: EvidenceRoute,
  RegisterRoute: RegisterRoute,
  ScanRoute: ScanRoute,
  VerifyRoute: VerifyRoute,
  ResultHashRoute: ResultHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
